spring:
  application:
    name: sharding-demo

server:
  port: 8090

master:
  equip0:
    url: jdbc:mysql://localhost:3306/equip_db_0?characterEncoding=utf8&useSSL=false
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
    databaseName: equip_db_0
  equip1:
    url: jdbc:mysql://localhost:3306/equip_db_1?characterEncoding=utf8&useSSL=false
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
    databaseName: equip_db_1
slave:
  equip0:
    url: jdbc:mysql://localhost:3306/equip_dbs_0?characterEncoding=utf8&useSSL=false
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
    databaseName: equip_dbs_0
  equip1:
    url: jdbc:mysql://localhost:3306/equip_dbs_1?characterEncoding=utf8&useSSL=false
    username: root
    password:
    driverClassName: com.mysql.cj.jdbc.Driver
    databaseName: equip_dbs_1

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

